### ISSUE TITLE
Question about your use of React and global variables.

### ISSUE THREAD

**Issue by josephdburdick** [eventedmind/feed-using-react-with-meteor#1]
Hi Chris, I was just investigating this and found that you're using React to render your front-end, even using the Router that comes with React instead of something like Iron Router. Interesting!

My first question is: I see you've defined your React components as global variables. I understand in Meteor we do this for Collections to keep them accessible at every level so *that* makes sense, and this isn't my first time seeing global variables being used  in Meteor for React, I just figure you're the *best* person to ask.. is there any other way? Is there any other way to include these components without adding them to the global scope?

One idea I've had is to create one single global variable and add things to do that, like so:
```
C = {};
C.List = React.createClass({ ... });
C.ListItem = React.createClass({ ... });
```

You have any thoughts on this? Thanks a bunch man, your classes really helped me out a while back. :metal:

**Comment by cmather** [comment]
Hey @josephdburdick, Thanks for the question. I'm using iron:router in this feed example, but hopefully I showed that it's pretty easy to use whatever routing solution you want.

I'm defining the react components as globals mostly for convenience, and so that I can play easily with them in the browser debugger. But name-spacing them, as you propose, is a great idea. When Meteor implements ES6 modules I think that will help a lot as well as you can "import" and "export" what you want.

**Comment by josephdburdick** [comment]
Ah, okay. Thanks for the answer, Chris!
